Prevent Fuzzilli from generating async generators during mutation
Summary:
Original Author: edq@fb.com
Original Git: 0cf060b09cf970369f45d8efb2558ecb5d566ef2

Hermes currently does not support [async generator functions](https://github.com/facebook/hermes/blob/b7d275dbc5c4ad6775ef757efcdd964f88382f8b/doc/Features.md?plain=1#L37), so let's prevent `AsyncGeneratorFunctionGenerator` from being selected by the `CodeGenMutator`

```test.js

async function* foo() {
  yield await Promise.resolve('bar');
}
```

```./hermes test.js
test.js:1:1: error: async generators are unsupported
async function* foo() {
^~~~~~~~~~~~~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Original Revision: D39601483

Reviewed By: tmikov

Differential Revision: D41240815

fbshipit-source-id: 7dfb2183a415e9d6f6cffb902c830a8f4c2e1a82